nome = input ("Digite o seu nome: ")
idade = input ("Digite a sua idade: ")
sexo = input ("Digite o seu sexo: ")
endereço = input ("Digite o seu endereço: ")
telefone = input ("Digite o seu telefone:")

print("\nSeu nome eh:", nome)
print("Sua idade eh:", idade)
print("Seu sexo eh:", sexo)
print("Seu endereço eh:", endereço)
print("Seu telefone eh:", telefone, "\n")